id: I2D4B1AB3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:02:19+00:00'
last_modified: '2022-06-08T03:26:11.799880+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1284
  title: སྒྱུ་མ་འཕྲུལ་གྱི་མན་ངག་གསང་བ་ཚིག་བརྒྱུད་བཀའ་རྒྱ་ཅན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    38FC:
      image_group_id: I1KG1292
      title: ''
      total_pages: 64
      order: 1
      base_file: 38FC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
